version: '2'
services:
    mongo2:
        container_name: "mongo2"
        image: mongo
        ports:
            - "30002:27017"
        command: mongod --replSet my-mongo-set --rest
        restart: always

    mongo3:
        container_name: "mongo3"
        image: mongo
        ports:
            - "30003:27017"
        command: mongod --replSet my-mongo-set --rest
        restart: always 

    mongo1:
        container_name: "mongo1"
        image: mongo
        ports:
            - "30001:27017"
        command: mongod --replSet my-mongo-set --rest
        links:
            - mongo2:mongo2
            - mongo3:mongo3
        restart: always

    mongosetup:
        image: mongo
        links:
            - mongo1:mongo1
            - mongo2:mongo2
            - mongo3:mongo3
        volumes:
            - ./scripts:/scripts
        entrypoint: [ "/scripts/setup.sh" ]
